Repository TUM-Dev/Campus-iOS, pull requests merged in 2018-06, with the labels that each got.

#249 Login Logo was not properly sized
  TUM Campus App/LoginViewController.swift
  TUM Campus App/Setup.storyboard
Labels: in progress

#254 Add Firebase integration
  Podfile
  Podfile.lock
  TUM Campus App.xcodeproj/project.pbxproj
  TUM Campus App/AppDelegate.swift
  TUM Campus App/GoogleService-Info.plist
Labels: enhancement, in progress

#257 Update News and NewsSource
  TUM Campus App/News.swift
  TUM Campus App/NewsSource.swift
Labels: in progress

#262 Update room finder
  TUM Campus App/RoomFinder.storyboard
  TUM Campus App/RoomFinderViewController.swift
Labels: UI, pls review

#259 Resize TUM logo to more pleasant size
  TUM Campus App/CardViewController.swift
  TUM Campus App/LoginViewController.swift
  TUM Campus App/Setup.storyboard
Labels: UI, in progress, pls review

#260 Implement card ordering
  TUM Campus App/BookRentalManager.swift
  TUM Campus App/CardKey.swift
  TUM Campus App/CardViewController.swift
  TUM Campus App/DataSources/ComposedDataSource.swift
  TUM Campus App/EditCardsViewController.swift
  TUM Campus App/LibrarySettingsViewController.swift
  TUM Campus App/More.storyboard
  TUM Campus App/MoreTableViewController.swift
  TUM Campus App/TumDataManager.swift
Labels: Work in Progress, in progress

#271 Filter newspread items from news card
  TUM Campus App/DataSources/NewsDataSource.swift
Labels: enhancement, in progress, pls review

#270 Update beta link
  TUM Campus App/config.json
Labels: enhancement, in progress, pls review

#273 Fix film poster size
  TUM Campus App/CardCells/RoundedLabel.swift
  TUM Campus App/CardCells/TUFilmCollectionViewCell.swift
  TUM Campus App/CardCells/TUFilmCollectionViewCell.xib
  TUM Campus App/DataSources/TUFilmDataSource.swift
Labels: in progress, pls review

#263 Fixed NavBar Glitch
  TUM Campus App/CardView.storyboard
  TUM Campus App/CardViewController.swift
Labels: in progress

#265 Implemented error view and network timeout
  TUM Campus App.xcodeproj/project.pbxproj
  TUM Campus App/CardViewController.swift
  TUM Campus App/DataSources/ComposedDataSource.swift
  TUM Campus App/ErrorView.swift
  TUM Campus App/ErrorView.xib
Labels: pls review

#261 Add card content interaction
  TUM Campus App.xcodeproj/project.pbxproj
  TUM Campus App/CalendarViewController.swift
  TUM Campus App/CardCells/CafeteriaCollectionViewCell.swift
  TUM Campus App/CardCells/CafeteriaCollectionViewCell.xib
  TUM Campus App/CardCells/CalendarCollectionViewCell.xib
  TUM Campus App/CardCells/DataSourceCollectionViewCell.swift
  TUM Campus App/CardCells/NewsCollectionViewCell.xib
  TUM Campus App/CardCells/RoundBackgroundWithShadow.swift
  TUM Campus App/CardCells/RoundBlurredBackground.swift
  TUM Campus App/CardCells/TUFilmCollectionViewCell.xib
  TUM Campus App/CardView.storyboard
  TUM Campus App/CardViewController.swift
  TUM Campus App/CollectionViewLayouts/UICollectionViewDelegateLandscapeItemFlowLayout.swift
  TUM Campus App/CollectionViewLayouts/UICollectionViewDelegateSingleItemFlowLayout.swift
  TUM Campus App/CollectionViewLayouts/UICollectionViewDelegateThreeItemHorizontalFlowLayout.swift
  TUM Campus App/CollectionViewLayouts/UICollectionViewDelegateThreeItemVerticalFlowLayout.swift
  TUM Campus App/DataSources/CafeteriaDataSource.swift
  TUM Campus App/DataSources/CalendarDataSource.swift
  TUM Campus App/DataSources/ComposedDataSource.swift
  TUM Campus App/DataSources/GradesDataSource.swift
  TUM Campus App/DataSources/LecturesDataSource.swift
  TUM Campus App/DataSources/MVGStationDataSource.swift
  TUM Campus App/DataSources/NewsDataSource.swift
  TUM Campus App/DataSources/NewsSpreadDataSource.swift
  TUM Campus App/DataSources/StudyRoomsDataSource.swift
  TUM Campus App/DataSources/TUFilmDataSource.swift
  TUM Campus App/DataSources/TuitionDataSource.swift
  TUM Campus App/GradesTableViewController.swift
  TUM Campus App/Lecture.storyboard
  TUM Campus App/MVGNearbyStationsViewController.swift
  TUM Campus App/Movie.storyboard
  TUM Campus App/MovieDetailTableViewController.swift
  TUM Campus App/NewsSpreadCollectionViewCell.xib
  TUM Campus App/NewsTableViewController.swift
  TUM Campus App/RefreshableTableViewController.swift
  TUM Campus App/StudyRoomGroup.swift
  TUM Campus App/StudyRoomsTableViewController.swift
Labels: in progress, pls review
