Repository TUM-Dev/Campus-iOS, pull requests merged in 2018-07, with the labels that each got.

#279 Fix empty study rooms list
  TUM Campus App/DataSources/StudyRoomsDataSource.swift
Labels: bug, in progress

#281 Enable device orientations
  TUM Campus App/AppDelegate.swift
  TUM Campus App/Info.plist
Labels: in progress

#282 Bump app version to 2.0
  TUM Campus App/Info.plist
Labels: in progress

#280 Fix wrong cell heights
  TUM Campus App.xcodeproj/project.pbxproj
  TUM Campus App/CardCells/TUFilmCollectionViewCell.swift
  TUM Campus App/CardCells/TUFilmCollectionViewCell.xib
  TUM Campus App/CardViewController.swift
  TUM Campus App/CollectionViewLayouts/ColumnsFlowLayoutDelegate.swift
  TUM Campus App/CollectionViewLayouts/FixedColumnsFlowLayoutDelegate.swift
  TUM Campus App/CollectionViewLayouts/FixedColumnsVerticalItemsFlowLayoutDelegate.swift
  TUM Campus App/CollectionViewLayouts/ListFlowLayoutDelegate.swift
  TUM Campus App/CollectionViewLayouts/UICollectionViewDelegateListFlowLayout.swift
  TUM Campus App/CollectionViewLayouts/UICollectionViewDelegateSingleItemFlowLayout.swift
  TUM Campus App/CollectionViewLayouts/UICollectionViewDelegateThreeItemHorizontalFlowLayout.swift
  TUM Campus App/CollectionViewLayouts/UICollectionViewDelegateThreeItemVerticalFlowLayout.swift
  TUM Campus App/CollectionViewLayouts/VariableColumnsFlowLayoutDelegate.swift
  TUM Campus App/DataSources/CafeteriaDataSource.swift
  TUM Campus App/DataSources/CalendarDataSource.swift
  TUM Campus App/DataSources/ComposedDataSource.swift
  TUM Campus App/DataSources/GradesDataSource.swift
  TUM Campus App/DataSources/LecturesDataSource.swift
  TUM Campus App/DataSources/MVGDepartureDataSource.swift
  TUM Campus App/DataSources/MVGStationDataSource.swift
  TUM Campus App/DataSources/MenuDataSource.swift
  TUM Campus App/DataSources/NewsDataSource.swift
  TUM Campus App/DataSources/NewsSpreadDataSource.swift
  TUM Campus App/DataSources/StudyRoomsDataSource.swift
  TUM Campus App/DataSources/TUFilmDataSource.swift
  TUM Campus App/DataSources/TuitionDataSource.swift
Labels: UI, in progress

#278 Added TUMPickerController, and removed AYSlidingPickerView
  Podfile
  Podfile.lock
  TUM Campus App.xcodeproj/project.pbxproj
  TUM Campus App/CafeteriaViewController.swift
  TUM Campus App/MovieDetailTableViewController.swift
  TUM Campus App/RoomFinderViewController.swift
  TUM Campus App/StudyRoomsTableViewController.swift
  TUM Campus App/TUMPickerController.swift
  TUM Campus App/TuitionTableViewController.swift
  TUM Campus App/Tution~.storyboard
Labels: in progress, pls review

#283 Properly add Crashlytics
  Podfile
  Podfile.lock
  TUM Campus App.xcodeproj/project.pbxproj
  TUM Campus App/AppDelegate.swift
Labels: enhancement, in progress

#284 Bump build number to 11
  TUM Campus App/Info.plist
Labels: in progress

#295 Beta link
  README.md
Labels: in progress

#292 Improve iPad experience
  TUM Campus App/Base.lproj/LaunchScreen.storyboard
  TUM Campus App/CalendarViewController.swift
  TUM Campus App/CardViewController.swift
  TUM Campus App/Tution.storyboard
Labels: in progress

#285 Make drop shadow of cells lighter
  TUM Campus App.xcodeproj/project.pbxproj
  TUM Campus App/CardCells/CalendarCollectionViewCell.xib
  TUM Campus App/CardCells/NewsCollectionViewCell.xib
  TUM Campus App/CardCells/RoundBackgroundWithShadow.swift
  TUM Campus App/CardCells/RoundBlurredBackground.swift
  TUM Campus App/CardCells/TUFilmCollectionViewCell.xib
  TUM Campus App/NewsSpreadCollectionViewCell.xib
Labels: UI, enhancement, in progress

#299 Fixed travis badge
  README.md
Labels: in progress

#301 Fixed search for iOS 10 users
  TUM Campus App/CardViewController.swift
Labels: in progress

#300 Fix dead roomfinder cell in MoreView
  TUM Campus App/CardViewController.swift
  TUM Campus App/More.storyboard
Labels: in progress

#302 Bump build number to 12
  TUM Campus App/Info.plist
Labels: in progress
